# Generated by Django 6.0.1 on 2026-02-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(default='changeme123', max_length=255),
            preserve_default=False,
        ),
    ]
