# Generated by Django 6.0.1 on 2026-02-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='password',
        ),
    ]
