# Generated by Django 6.0.1 on 2026-02-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_business_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100)),
                ('language', models.CharField(default='english', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='db_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['email', 'is_approved'], name='core_busine_email_6f5879_idx'),
        ),
        migrations.AlterModelTable(
            name='business',
            table='core_business',
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('module', 'slug', 'language')},
        ),
    ]
