# Generated by Django 6.0.1 on 2026-02-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_role_emailtemplate_core_emailt_module_211275_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.TextField(default='Basic'),
        ),
    ]
