# Generated by Django 6.0.1 on 2026-02-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_proposal_adjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='assigned',
            new_name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Pending'), ('3', 'Approved')], default='1', max_length=20),
        ),
    ]
