# Generated by Django 6.0.1 on 2026-02-20 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_proposal_status_remove_proposal_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Pending'), ('3', 'Approved')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
