# Generated by Django 6.0.1 on 2026-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_proposal_adjustment_proposal_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Office', 'Office')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Not Invoiced', max_length=50)),
            ],
        ),
    ]
