# Generated by Django 6.0.1 on 2026-03-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_invoiceemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceemaillog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.invoice'),
        ),
    ]
