# Generated by Django 6.0.1 on 2026-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]