# Generated by Django 6.0.1 on 2026-03-11 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20260310_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_zip',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_zip',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estimate'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='default_language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('Null', 'Null'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('UPI', 'UPI')], default='Bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
