# Generated by Django 6.0.1 on 2026-03-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_client_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='core.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.estimate'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='core.invoice'),
        ),
    ]
