# Generated by Codex on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    # The previous migration that created proxy models has been removed.
    # This migration now depends only on the activity log migration.
    dependencies = [
        ("core", "0046_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="proposal_to",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="zip",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="email",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

