# Generated by Codex on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_proposal_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="comments",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="reminders",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="tasks",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="notes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]

