# Generated by Django 6.0.1 on 2026-03-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_proposal_activity_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=191, unique=True)),
                ('slug', models.SlugField(max_length=191, unique=True)),
                ('content', models.TextField()),
                ('variable_keys', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_contract_template',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('name', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_currency',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupCustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=191, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_customer_group',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_expense_category',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupGDPRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('module_slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('request_type', models.CharField(choices=[('export', 'Data Export'), ('delete', 'Data Deletion'), ('rectify', 'Data Rectification'), ('consent', 'Consent Update')], default='export', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_gdpr_request',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SetupHelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('slug', models.SlugField(max_length=191, unique=True)),
                ('module_slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_help_article',
                'ordering': ['module_slug', 'sort_order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupLeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_lead_source',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupLeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_lead_status',
                'ordering': ['sequence', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=80, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_module',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupPaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_payment_mode',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupSupportDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_support_department',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_tax',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupThemeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('accent_color', models.CharField(default='#198754', max_length=7)),
                ('ui_settings', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_theme_style',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupTicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_ticket_priority',
                'ordering': ['level', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupTicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('color', models.CharField(default='#0d6efd', max_length=7)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_ticket_status',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesProposal',
            fields=[
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.proposal',),
        ),
        migrations.CreateModel(
            name='SetupCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=191)),
                ('field_key', models.SlugField(max_length=191)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox')], default='text', max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_custom_field',
                'ordering': ['module_slug', 'sort_order', 'id'],
                'unique_together': {('module_slug', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='SetupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=191)),
                ('value', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('boolean', 'Boolean'), ('json', 'JSON')], default='text', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_setup_setting',
                'ordering': ['category', 'display_name', 'id'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SetupPredefinedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=191)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predefined_replies', to='core.setupsupportdepartment')),
            ],
            options={
                'db_table': 'core_setup_predefined_reply',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SetupCustomerGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_group_assignments', to='core.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='core.setupcustomergroup')),
            ],
            options={
                'db_table': 'core_setup_customer_group_assignment',
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('customer',)},
            },
        ),
        migrations.CreateModel(
            name='SetupRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.SlugField(max_length=120)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_permissions', to='core.role')),
            ],
            options={
                'db_table': 'core_setup_role_permission',
                'ordering': ['role_id', 'module_slug', 'id'],
                'unique_together': {('role', 'module_slug')},
            },
        ),
    ]
