# Generated by Django 6.0.1 on 2026-03-30 04:15

from django.db import migrations, models


def add_columns_if_missing(apps, schema_editor):
    """Add address columns to ``core_contact`` if they do not already exist.

    MySQL prior to 8.0 does not support ``ADD COLUMN IF NOT EXISTS``.
    Instead we execute a plain ``ALTER TABLE`` for each column and ignore
    the error if the column is already present. This approach works for
    both MySQL versions that support the ``IF NOT EXISTS`` clause and those
    that do not.
    """
    from django.db import DatabaseError

    sql_statements = [
        "ALTER TABLE core_contact ADD COLUMN street varchar(255) NULL;",
        "ALTER TABLE core_contact ADD COLUMN city varchar(100) NULL;",
        "ALTER TABLE core_contact ADD COLUMN state varchar(100) NULL;",
        "ALTER TABLE core_contact ADD COLUMN zip_code varchar(20) NULL;",
        "ALTER TABLE core_contact ADD COLUMN country varchar(100) NULL;",
    ]
    for sql in sql_statements:
        try:
            schema_editor.execute(sql)
        except DatabaseError:
            # Column probably already exists; ignore and continue.
            continue


class Migration(migrations.Migration):
    # MySQL cannot execute DDL statements inside a transaction, so we disable
    # the atomic transaction wrapper for this migration.
    atomic = False

    dependencies = [
        ('core', '0053_customfieldvalue'),
    ]

    operations = [
        migrations.RunPython(add_columns_if_missing, reverse_code=migrations.RunPython.noop),
    ]
