# Generated by Django 6.0.1 on 2026-03-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_activity_log_table'),
        ('core', '0056_add_contact_address_fields_sql'),
    ]

    operations = [
    ]
