# Generated by Django 6.0.1 on 2026-03-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_merge_20260331_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ms_business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminClient',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.client',),
        ),
        migrations.CreateModel(
            name='AdminContact',
            fields=[
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        # NOTE: The original migration attempted to rename an index that no longer exists.
        # This RenameIndex operation caused a migration failure (OperationalError 1176).
        # The index `core_project_client__e37d5a_idx` was either never created or was
        # removed in a later migration. Since the rename is not required for any
        # functional change, we safely omit it.
    ]
