# Generated by Django 6.0.1 on 2026-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_setuphelparticle_inquiry_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setupcustomfield',),
        ),
        migrations.AddField(
            model_name='creditnotereminder',
            name='created_by',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='creditnotetask',
            name='created_by',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='invoicereminder',
            name='created_by',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='invoicetask',
            name='created_by',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
