# Generated by Django 6.0.1 on 2026-04-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_repair_created_by_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupthemestyle',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='setupthemestyle',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='navbar_bg',
            field=models.CharField(default='#011e34', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='navbar_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='sidebar_bg',
            field=models.CharField(default='#011e34', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='sidebar_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='status_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='status_error',
            field=models.CharField(default='#dc3545', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='status_info',
            field=models.CharField(default='#17a2b8', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='status_success',
            field=models.CharField(default='#28a745', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='status_warning',
            field=models.CharField(default='#ffc107', max_length=7),
        ),
        migrations.AddField(
            model_name='setupthemestyle',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
