# Generated by Django 6.0.1 on 2026-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_support_module_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_ticket',
                'ordering': ['-created_at', '-ticket_id'],
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=191),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
