# Generated by Django 6.0.1 on 2026-02-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
