# Generated by Django 6.0.1 on 2026-02-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0002_alter_activitylog_options_alter_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='staffid',
            new_name='staff_name',
        ),
    ]
