# Generated by Django 6.0.1 on 2026-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0003_rename_staffid_activitylog_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='staffid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
