# Generated by Django 6.0.1 on 2026-02-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0004_remove_activitylog_staff_name_activitylog_staffid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'managed': False},
        ),
    ]
