# Generated by Django 6.0.1 on 2026-02-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0005_alter_activitylog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
    ]
