# Generated by Django 6.0.1 on 2026-02-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0007_alter_roles_name_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
