# Generated by Django 4.2.3 on 2026-04-03

from django.db import migrations, models
import django.db.models.deletion


def seed_leads_defaults(apps, schema_editor):
    ProductStatus = apps.get_model("ms_crm_app", "ProductStatus")
    CustomerStatus = apps.get_model("ms_crm_app", "CustomerStatus")
    LeadSource = apps.get_model("ms_crm_app", "LeadSource")

    for status_name in ["Active", "Inactive"]:
        ProductStatus.objects.get_or_create(name=status_name)

    for customer_status_name in ["New", "Interested", "Converted"]:
        CustomerStatus.objects.get_or_create(
            name=customer_status_name,
            defaults={"is_active": True},
        )

    for source_name in ["Website", "Email", "Manual"]:
        LeadSource.objects.get_or_create(name=source_name)


def unseed_leads_defaults(apps, schema_editor):
    ProductStatus = apps.get_model("ms_crm_app", "ProductStatus")
    CustomerStatus = apps.get_model("ms_crm_app", "CustomerStatus")
    LeadSource = apps.get_model("ms_crm_app", "LeadSource")

    ProductStatus.objects.filter(name__in=["Active", "Inactive"]).delete()
    CustomerStatus.objects.filter(name__in=["New", "Interested", "Converted"]).delete()
    LeadSource.objects.filter(name__in=["Website", "Email", "Manual"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ms_crm_app", "0011_announcements_clients_consentpurposes_consents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ms_customer_statuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_host", models.CharField(max_length=255)),
                ("email_port", models.PositiveIntegerField(default=993)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("is_connected", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ms_leads_email_integrations",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LeadSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "ms_lead_sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ms_lead_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "ms_product_statuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebFormField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("field_name", models.CharField(db_index=True, max_length=120, unique=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("dropdown", "Dropdown"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("number", "Number"),
                            ("textarea", "Textarea"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ms_web_form_fields",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, default="", max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="ms_crm_app.customerstatus",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="ms_crm_app.product",
                    ),
                ),
                (
                    "product_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="ms_crm_app.productstatus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="ms_crm_app.leadsource",
                    ),
                ),
            ],
            options={
                "db_table": "ms_crm_leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["customer_status"], name="ms_lead_cust_idx"),
                    models.Index(fields=["source"], name="ms_lead_source_idx"),
                    models.Index(fields=["product"], name="ms_lead_product_idx"),
                    models.Index(fields=["product_status"], name="ms_lead_prdstat_idx"),
                    models.Index(fields=["created_at"], name="ms_lead_created_idx"),
                ],
            },
        ),
        migrations.RunPython(seed_leads_defaults, unseed_leads_defaults),
    ]
