# Generated by Django 6.0.1 on 2026-04-15 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_crm_app', '0012_leads_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCaptureConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=60, unique=True)),
                ('is_web_to_lead_enabled', models.BooleanField(default=True)),
                ('require_api_key', models.BooleanField(default=False)),
                ('api_key_token', models.CharField(blank=True, default='', max_length=255)),
                ('default_source', models.CharField(blank=True, default='Website', max_length=120)),
                ('default_status', models.CharField(blank=True, default='New', max_length=120)),
                ('default_priority', models.CharField(blank=True, default='medium', max_length=30)),
                ('default_product', models.CharField(blank=True, default='', max_length=255)),
                ('default_product_status', models.CharField(blank=True, default='', max_length=120)),
                ('auto_assign_user', models.CharField(blank=True, default='', max_length=120)),
                ('auto_assign_team', models.CharField(blank=True, default='', max_length=120)),
                ('prevent_duplicates', models.BooleanField(default=True)),
                ('send_notification_email', models.BooleanField(default=False)),
                ('notification_email', models.CharField(blank=True, default='', max_length=255)),
                ('send_auto_response', models.BooleanField(default=False)),
                ('auto_response_subject', models.CharField(blank=True, default='', max_length=255)),
                ('auto_response_message', models.TextField(blank=True, default='')),
                ('recaptcha_enabled', models.BooleanField(default=False)),
                ('recaptcha_site_key', models.CharField(blank=True, default='', max_length=255)),
                ('recaptcha_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ms_lead_capture_configuration',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='webformfield',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='auto_create_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='imap_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='emailintegration',
            name='use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to_team',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, default='', max_length=191),
        ),
        migrations.AddField(
            model_name='lead',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, default='medium', max_length=30),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webformfield',
            name='field_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webformfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webformfield',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='webformfield',
            name='mapped_field',
            field=models.CharField(blank=True, default='dynamic', max_length=60),
        ),
        migrations.AddField(
            model_name='webformfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=191),
        ),
        migrations.AddField(
            model_name='webformfield',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailintegration',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailintegration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailintegration',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'USER'), (3, 'STORE_MANAGER'), (4, 'PRODUCTION_MANAGER'), (5, 'QUALITY_CONTROL'), (6, 'PURCHASE_MANAGER')], null=True),
        ),
    ]
